### ISSUE TITLE
error running plan

### ISSUE THREAD

**Issue by anewton1980** [cloudposse/terraform-aws-vpc-peering-multi-account#17]
When I run terraform plan I get the below error

module.vpc_peering_cross_account: eval: *terraform.EvalLocal, err: Missing resource instance key: Because data.aws_route_tables.accepter has "count" set, its attributes must be accessed on specific instances.

For example, to correlate with indices of a referring resource, use:
    data.aws_route_tables.accepter[count.index]

**Comment by njgerner** [comment]
Related to #12. Update your source to the following until PR 16 is merged:
```
source    = "git::https://github.com/cloudposse/terraform-aws-vpc-peering-multi-account.git?ref=terraform-0.12"
```

**Comment by SweetOps** [comment]
has been resolved by  https://github.com/cloudposse/terraform-aws-vpc-peering-multi-account/pull/29
