### ISSUE TITLE
Add profile as provider option

### ISSUE THREAD

**Issue by msmagoo87** [cloudposse/terraform-aws-vpc-peering-multi-account#7]
The way we have set up our accounts is we have one auth account and then every other account in our org has an assume role that the auth account can assume. This means that when we use the aws cli, we have a base profile (that we don't set as default for security reasons) with credentials and then every other profile is an assume role with that base profile as the source profile. So when using this module, it does not work because I have no way of specifying the profile I want the provider to use. Can this be added?

So for example, this is how we set up our providers:
```
provider "aws" {
  alias           = "other-account"
  region          = "us-east-1"
  profile         = "ops"
  assume_role {
    role_arn      = "arn:aws:iam::XXXXXXXXXXXX:role/peering-assume-role"
  }
}
```

**Comment by AndrewPotterIrwin** [comment]
This change would be extremely helpful for us for our Organizations set up as we could run all requests from the master account. We could use the "OrganizationAccountAccessRole" which is created by default in each child account. This would then remove the requirement to set up additional roles in each account for peering.

**Comment by aknysh** [comment]
thanks @msmagoo87, nice suggestion
can you open a PR for that? we'll review promptly

will it work if `profile` is empty by default?

```
provider "aws" {
  alias           = "other-account"
  region          = "us-east-1"
  profile         = "var.profile"
  assume_role {
    role_arn      = "arn:aws:iam::XXXXXXXXXXXX:role/peering-assume-role"
  }
}

variable "profile" {
  type        = "string"
  description = "......."
  default     = ""
}

```

**Comment by msmagoo87** [comment]
Good question, @aknysh, I am not sure. Would warrant some testing.
Although this is useful for sure, it turns out it won't solve my problem. Unfortunately MFA is the issue that I'm actually having which is apparently a notorious issue with terraform. I am in the process of doing some experimentation but I don't think this problem will be solved anytime soon and we'll likely have to work around it instead. I can still submit a PR for this change, however.

**Comment by AndrewPotterIrwin** [comment]
I am running a fork of this with profile set which works fine. I can do some testing to see if it works with it left blank and update on my findings.
